'use client';

import { Activity, AlertTriangle, ArrowRight, Bookmark, Bot, Braces, ChevronRight, CircleHelp, Clock3, Database, Eye, History, Radar, Search, ShieldCheck, Sparkles, TimerReset, WalletCards, UsersRound } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { providerLabel, type Chain, type Opportunity, type Stage } from '@/lib/opportunity';

const API = 'https://mdc-ingestion.wanglujie1987.workers.dev';
type View = '机会流' | '信源画像' | '历史研究' | '自选' | '详情';
type Live = { id:string; name:string; ticker:string|null; stage:Stage; score:number; first_seen_at:string; last_seen_at:string; independent_author_count:number; post_count:number; scan_count:number; summary:string|null; risk:string|null; dex_status:string|null; chain_id:string|null; dex_id:string|null; pair_address:string|null; token_address:string|null; liquidity_usd:number|null; market_cap_usd:number|null };
type Scan = {source:string;status:string;query_count:number;post_count:number;candidate_count:number;started_at:string;dex_deferred_count?:number}|null;
type Source = {author_handle:string;first_observed_at:string;total_signals:number;discovery_signals:number;prediction_signals:number;resolved_outcomes:number;accuracy:number|null};
type DetailData = {evidence:Array<{tweet_id:string;author_handle:string|null;observed_at:string;content:string|null;source_url:string|null}>};
const stages:Stage[]=['社媒初筛','待链上验证','未发币','候选合约','刚发币待验证','已验证未拥挤','已排除'];

function date(value?:string|null){return value?new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value)):'—'}
function chain(id:string|null):Chain{return id==='bsc'?'BNB Chain':id==='solana'?'Solana':id==='robinhood'?'Robinhood Chain':'未确认'}
function mapLive(row:Live):Opportunity{const matched=row.dex_status==='direct_contract_match'||row.dex_status==='corroborated_match';return {id:row.id,name:row.name,ticker:row.ticker??'—',stage:row.stage,score:row.score,discovered:date(row.first_seen_at),firstObservedAt:row.first_seen_at,velocity:String(row.independent_author_count)+' 个独立账号',narrative:row.summary??'系统正在汇总叙事证据。',risk:row.risk??'尚未完成风险评估',evidence:String(row.post_count)+' 条帖子 · '+String(row.scan_count)+' 次扫描',automated:matched?'已完成合约归因':'等待链上核验',sources:[{provider:'socialdata',platform:'x',label:String(row.post_count)+' 条可追溯 X 证据',observedAt:row.last_seen_at}],tokenCandidates:matched?[{chain:chain(row.chain_id),address:row.token_address??undefined,pairAddress:row.pair_address??undefined,dexId:row.dex_id??undefined,liquidityUsd:row.liquidity_usd??undefined,marketCapUsd:row.market_cap_usd??undefined,verified:true}]:[]}}

export default function Home(){
 const [view,setView]=useState<View>('机会流'),[selected,setSelected]=useState<Opportunity|null>(null),[saved,setSaved]=useState<string[]>([]),[filter,setFilter]=useState<Stage|'全部'>('全部'),[queue,setQueue]=useState<'priority'|'watch'>('priority'),[query,setQuery]=useState(''),[live,setLive]=useState<{opportunities:Live[];latestScan:Scan;methodology:string}|null>(null),[sources,setSources]=useState<Source[]|null>(null),[error,setError]=useState<string|null>(null);
 useEffect(()=>{let on=true;Promise.all([fetch(API+'/opportunities?limit=100').then(r=>r.ok?r.json():Promise.reject(new Error('机会接口返回 '+r.status))) as Promise<{opportunities:Live[];latestScan:Scan;methodology:string}>,fetch(API+'/sources?limit=100').then(r=>r.ok?r.json():Promise.reject(new Error('信源接口返回 '+r.status))) as Promise<{sources:Source[]}>]).then(([o,s])=>{if(on){setLive(o);setSources(s.sources??[]);setError(null)}}).catch((e:Error)=>on&&setError(e.message));return()=>{on=false}},[]);
 const items=live?live.opportunities.map(mapLive):[], save=(id:string)=>setSaved(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]),open=(item:Opportunity)=>{setSelected(item);setView('详情')};
 return <main className="mdc"><header><button className="brand" onClick={()=>setView('机会流')}><span className="brandMark"><Radar size={19}/></span><span><b>Meme Channel</b><small>多链梗币研究台</small></span></button><div className="engine"><i/> 多链监控运行中 <em/> BNB · SOL · ROBINHOOD</div><button className="avatar">MC</button></header><nav>{(['机会流','信源画像','历史研究','自选'] as View[]).map(x=><button key={x} onClick={()=>setView(x)} className={view===x?'on':''}>{x}</button>)}<span/><label className="search"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索叙事 / 代币" aria-label="搜索叙事或代币"/></label></nav>{view==='机会流'&&<Feed items={items} scan={live?.latestScan??null} methodology={live?.methodology} fallback={!live} error={error} filter={filter} setFilter={setFilter} queue={queue} setQueue={setQueue} query={query} saved={saved} save={save} open={open}/>} {view==='详情'&&selected&&<Detail item={selected} back={()=>setView('机会流')} saved={saved.includes(selected.id)} save={save}/>} {view==='信源画像'&&<Sources profiles={sources} error={error}/>} {view==='历史研究'&&<Research/>} {view==='自选'&&<Watchlist items={items} saved={saved} open={open}/>}</main>
}

function Feed({items,scan,methodology,fallback,error,filter,setFilter,queue,setQueue,query,saved,save,open}:{items:Opportunity[];scan:Scan;methodology?:string;fallback:boolean;error:string|null;filter:Stage|'全部';setFilter:(x:Stage|'全部')=>void;queue:'priority'|'watch';setQueue:(x:'priority'|'watch')=>void;query:string;saved:string[];save:(id:string)=>void;open:(x:Opportunity)=>void}){
 const ranked=useMemo(()=>[...items].sort((a,b)=>{const weight:{[key:string]:number}={'候选合约':5,'待链上验证':4,'未发币':3,'刚发币待验证':2,'社媒初筛':1,'已验证未拥挤':0,'已排除':-1};return (weight[b.stage]*1000+b.score)-(weight[a.stage]*1000+a.score)}),[items]);
 const filtered=(filter==='全部'?ranked:ranked.filter(x=>x.stage===filter)).filter(x=>!query||[x.name,x.ticker,x.narrative].join(' ').toLowerCase().includes(query.toLowerCase())), priority=filtered.slice(0,5), watch=filtered.slice(5), shown=queue==='priority'?priority:watch, status=scan?.status==='completed'?'已完成':scan?.status==='partial'?'部分完成':scan?.status==='failed'?'失败':'等待数据';
 return <section className="frame"><section className="signalHero"><div className="heroCopy"><p className="eyebrow"><Sparkles size={14}/> LIVE INTELLIGENCE FEED</p><p className="heroKicker">Meme Channel / 多链叙事雷达</p><h1>把注意力留给<br/><mark>真正需要核验的信号。</mark></h1><p>系统将社媒扩散、独立作者与合约归因拆开验证。这里不是热度榜，而是你的研究起点。</p><div className="heroMeta"><span><i/>数据流在线</span><span>每 3 小时自动扫描</span></div></div><div className="radarPanel"><div className="radarOrbit orbitOne"/><div className="radarOrbit orbitTwo"/><div className="radarSweep"/><div className="radarCenter"><Radar size={27}/><b>SCAN</b><small>{status}</small></div><div className="radarNode nodeX">X <small>{scan?.post_count??'—'}</small></div><div className="radarNode nodeDex">DEX <small>{scan?.dex_deferred_count?'retry':'live'}</small></div><div className="radarNode nodeChain">3<br/><small>CHAINS</small></div></div></section>
 <section className="telemetry"><div><span>最近扫描</span><b>{scan?date(scan.started_at):'连接中'}</b><small>{scan?.source??'实时接口'}</small></div><div><span>X 查询</span><b>{scan?.query_count??'—'}</b><small>当前关键词组</small></div><div><span>原始帖子</span><b>{scan?.post_count??'—'}</b><small>已进入去重聚类</small></div><div className="telemetryStatus"><Activity size={18}/><span><b>{status}</b><small>{scan?.dex_deferred_count?String(scan.dex_deferred_count)+' 个 Dex 核验延后重试':'验证流水线运行中'}</small></span></div></section>
 {fallback&&<div className="dataNotice warning"><AlertTriangle size={15}/><span><b>正在连接实时研究数据。</b>{error?' 当前不可用：'+error:' 页面不会混入演示候选。'}</span></div>}{!fallback&&items.length===0&&<div className="dataNotice"><Activity size={15}/><span><b>实时数据已连接，但尚无可展示机会。</b> 下一轮扫描会自动更新此队列。</span></div>}
 <section className="chainbar"><div><span>已覆盖链路</span><b className="bnb">BNB Chain</b><b className="sol">Solana</b><b className="rh">Robinhood Chain</b><b className="more">持续扩展</b></div><small>社媒信号与链上项目分开归因，避免同名币误配。</small></section>
 <section className="feedHead"><div><p className="eyebrow"><Radar size={14}/> RESEARCH QUEUE</p><h2>{queue==='priority'?'本轮优先研究':'观察池 / 不抢占注意力'}</h2></div><p>{methodology??'排序：传播独立性 × 跨轮出现 × 合约可验证性'}</p></section><div className="queueSwitch"><button className={queue==='priority'?'chosen':''} onClick={()=>setQueue('priority')}>优先研究 <b>{priority.length}/5</b></button><button className={queue==='watch'?'chosen':''} onClick={()=>setQueue('watch')}>观察池 <b>{watch.length}</b></button><small>只突出五个；其余信号继续沉淀。</small></div><div className="filters"><button className={filter==='全部'?'chosen':''} onClick={()=>setFilter('全部')}>全部 <b>{items.length}</b></button>{stages.map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?'chosen':''}>{x} <b>{items.filter(i=>i.stage===x).length}</b></button>)}</div>
 <div className="focusGrid">{shown.length?<><div className="focusLead"><Card item={shown[0]} index={0} saved={saved.includes(shown[0].id)} save={save} open={open} featured/></div><div className="focusList">{shown.slice(1).map((x,i)=><Card key={x.id} item={x} index={i+1} saved={saved.includes(x.id)} save={save} open={open}/>)}</div></>:<div className="empty"><Radar size={22}/><h2>没有符合当前筛选的实时候选</h2><p>系统会在下一轮扫描后自动刷新。</p></div>}<aside className="sidebar"><div className="pipeline"><p><Database size={14}/> 验证路径</p><div><Step n="01" title="社媒" copy="独立传播" active/><Step n="02" title="归因" copy="地址 / 官网"/><Step n="03" title="链上" copy="池子 / 风险"/></div></div><div className="ruleCard"><ShieldCheck size={17}/><h3>机会分，不是涨幅预测</h3><p>分数只表示证据密度与传播强度。没有完成合约归因的叙事，永远停留在待核验状态。</p></div><div className="ruleCard warning"><AlertTriangle size={17}/><h3>自动拦截</h3><p>单账号推广、收益喊单与泛用 ticker 不会被包装成可研究机会。</p></div></aside></div><HistoryStrip/><ResearchGuide/><AgentStory/></section>
}
function Step({n,title,copy,active=false}:{n:string;title:string;copy:string;active?:boolean}){return <article className={active?'active':''}><span>{n}</span><b>{title}</b><small>{copy}</small></article>}
function Card({item,index,saved,save,open,featured=false}:{item:Opportunity;index:number;saved:boolean;save:(id:string)=>void;open:(x:Opportunity)=>void;featured?:boolean}){const c=item.tokenCandidates[0]?.chain,providers=[...new Set(item.sources.map(x=>x.provider))];return <article className={'opp stage-'+item.stage+(featured?' featured':'')} onClick={()=>open(item)}>{featured&&<div className="featuredLabel"><Sparkles size={13}/> TOP SIGNAL</div>}<div className={'glyph g'+(index%5)}>{item.name[0]}</div><div className="oppbody"><div><h2>{item.name} <small>{item.ticker}</small></h2>{c&&<span className="chainTag">{c}</span>}<label>{item.stage}</label></div><p>{item.narrative}</p><aside><Clock3 size={12}/>首次发现 {item.discovered}<em/> <Activity size={12}/>{item.evidence}</aside><div className="sourceTags">{providers.map(x=><span key={x}>{providerLabel(x)}</span>)}</div></div><div className="machine"><span>{item.automated}</span><b>{item.score}</b><small>机会分</small><strong>{item.velocity}</strong></div><button className="save" aria-label="加入自选" onClick={e=>{e.stopPropagation();save(item.id)}}><Bookmark size={17} fill={saved?'currentColor':'none'}/></button><ChevronRight className="openArrow" size={18}/></article>}
function Detail({item,back,saved,save}:{item:Opportunity;back:()=>void;saved:boolean;save:(id:string)=>void}){const [detail,setDetail]=useState<DetailData|null>(null);useEffect(()=>{let on=true;(fetch(API+'/opportunities/'+encodeURIComponent(item.id)).then(r=>r.ok?r.json():Promise.reject()) as Promise<DetailData>).then(x=>on&&setDetail(x)).catch(()=>on&&setDetail(null));return()=>{on=false}},[item.id]);const evidence=detail?.evidence??[];return <section className="frame detail"><button className="back" onClick={back}>← 返回机会流</button><div className="detailTitle"><div><p className="eyebrow"><CircleHelp size={14}/> AUTOMATED RESEARCH CARD</p><h1>{item.name} <mark>· {item.stage}</mark></h1><p>由自动监控生成；结论随传播结构、合约归因与链上风险实时更新。</p></div><button className="bookmark" onClick={()=>save(item.id)}><Bookmark size={16} fill={saved?'currentColor':'none'}/>{saved?'已加入自选':'加入自选'}</button></div><div className="verdict"><div><span>系统结论</span><h2>{item.stage==='未发币'?'继续追踪叙事，尚不可交易':item.stage==='已排除'?'排除：不构成可信机会':'需要进一步验证'}</h2><p>{item.risk}。本页面不是交易建议。</p></div><div><span>最大风险</span><b>{item.risk}</b></div><div><span>状态有效期</span><b>下次扫描后重估</b></div></div><section className="detailGrid"><div className="panel"><h2>机器证据链</h2>{[['叙事发现',item.discovered+' · 自动聚类完成'],['传播验证',item.evidence],['合约归因',item.tokenCandidates[0]?.chain??'尚未发现可信合约'],['链上健康度','等待池子 / 持仓数据完整']].map(([a,b],i)=><div className="evidence" key={a}><i className={i<2?'good':''}/><p><b>{a}</b>{b}</p></div>)}</div><div className="panel"><h2>来源与可追溯证据</h2>{evidence.length?evidence.map(x=><div className="evidence sourceEvidence" key={x.tweet_id}><i className="good"/><p><b>{x.author_handle?'@'+x.author_handle:'X 来源'}</b>{x.content??'原始内容保存中'}<small>{date(x.observed_at)} · {x.source_url?<a href={x.source_url} target="_blank" rel="noreferrer">查看原帖</a>:'链接暂不可用'}</small></p></div>):item.sources.map(x=><div className="evidence sourceEvidence" key={x.observedAt}><i className="good"/><p><b>{providerLabel(x.provider)}</b>{x.label}<small>{date(x.observedAt)}</small></p></div>)}</div></section></section>}
function Sources({profiles,error}:{profiles:Source[]|null;error:string|null}){return <section className="frame"><div className="researchHero"><p className="eyebrow"><UsersRound size={14}/> SOURCE INTELLIGENCE</p><h1>不把账号叫“大神”。<br/><mark>只保留可验证的信源轨迹。</mark></h1><p>系统记录一个账号在哪些叙事上首次出现、是否给出明确方向，以及这些信号在结果可验证后如何表现。</p></div><section className="sourceMethod"><ShieldCheck size={18}/><div><b>当前方法：先积累，后排名</b><p>准确率只在有足够可验证结果后展示；现在不因少量样本对账号做收益承诺或排行。</p></div></section>{profiles===null?<div className="empty"><Activity size={22}/><h2>正在读取信源画像</h2><p>{error?'接口暂不可用：'+error:'等待实时接口返回。'}</p></div>:profiles.length===0?<div className="empty"><UsersRound size={22}/><h2>信源档案正在积累</h2><p>新的候选帖子会自动形成账号画像；当前尚无足够的已入库信源记录。</p></div>:<div className="sourceTable"><div className="sourceHead"><span>账号</span><span>信号</span><span>首次发现</span><span>明确预测</span><span>结果状态</span></div>{profiles.map(x=><article key={x.author_handle}><span><b>@{x.author_handle}</b><small>收录于 {date(x.first_observed_at)}</small></span><b>{x.total_signals}</b><b>{x.discovery_signals}</b><b>{x.prediction_signals}</b><span>{x.resolved_outcomes?<><b>{x.accuracy===null?'—':Math.round(x.accuracy*100)+'%'}</b><small>{x.resolved_outcomes} 个已验证结果</small></>:<><b>积累中</b><small>尚无可验证结果</small></>}</span></article>)}</div>}</section>}
function HistoryStrip(){return <section className="historyStrip"><div className="historyTop"><div><p className="eyebrow"><History size={14}/> OUTCOME TRACKING</p><h2>结果追踪已启动，等待可信合约进入样本池。</h2><p>确认归因后，系统会记录 24 小时价格与流动性变化；只有明确预测才会进入信源准确率计算。</p></div><span className="trackingState"><TimerReset size={15}/> 自动积累中</span></div></section>}
function ResearchGuide(){return <section className="researchGuide"><div><p className="eyebrow"><CircleHelp size={14}/> HOW TO USE MEME CHANNEL</p><h2>先看证据，再看合约，最后才决定是否继续研究。</h2><p>网站把“社媒热度”和“合约可信度”拆开呈现，避免同名币、转发刷量和单一喊单被误认为机会。</p></div><ol><li><b>01</b><span><strong>从优先研究开始</strong><small>每次只保留五个最值得核验的叙事。</small></span></li><li><b>02</b><span><strong>打开详情查看原帖</strong><small>确认独立作者、传播次数与风险说明。</small></span></li><li><b>03</b><span><strong>只对已归因合约继续跟踪</strong><small>没有合约地址或交叉证据，就停留在待验证阶段。</small></span></li></ol></section>}
function AgentStory(){return <section className="agentStory"><div className="agentCopy"><p className="eyebrow"><Bot size={14}/> FOR EXTERNAL AGENTS · PLANNED</p><h2>当你不在看盘，<mark>Agent 也能读懂机会。</mark></h2><p>未来，每个可验证机会都会成为机器可读事件：叙事、链、合约、证据、风险与失效时间一并交给外部 Agent。</p><div className="agentBadges"><span><Braces size={14}/> 只读 Opportunity API</span><span><ShieldCheck size={14}/> 证据与风险字段</span></div></div><div className="agentFlow"><div><Radar size={19}/><b>MDC Signals</b><small>多链机会研究</small></div><ArrowRight/><div><Bot size={19}/><b>Your Agent</b><small>按你的规则判断</small></div><ArrowRight/><div><WalletCards size={19}/><b>Your Wallet</b><small>你自行授权与签名</small></div></div><footer>我们提供信号，不托管资金、不替用户交易。<span>External Agent API · 即将开放</span></footer></section>}
function Research(){return <section className="frame"><div className="researchHero"><p className="eyebrow"><History size={14}/> OUTCOME RESEARCH</p><h1>不先写结论。<br/><mark>先等可验证结果。</mark></h1><p>可信合约出现后，系统才会建立 24 小时价格与流动性基准，并保留上涨、风险与中性结果。</p></div><div className="empty"><History size={22}/><h2>结果样本积累中</h2><p>当前没有可公开展示的已结算合约样本；不会用外部历史涨幅冒充本系统研究成果。</p></div></section>}
function Watchlist({items,saved,open}:{items:Opportunity[];saved:string[];open:(x:Opportunity)=>void}){const picks=items.filter(x=>saved.includes(x.id));return <section className="frame"><div className="researchHero"><p className="eyebrow"><Eye size={14}/> WATCHLIST</p><h1>只追踪你真正关心的变化。</h1><p>系统只在合约出现、归因确认、风险升高或机会失效时更新状态。</p></div>{picks.length?<div className="opps">{picks.map((x,i)=><Card key={x.id} item={x} index={i} saved save={()=>{}} open={open}/>)}</div>:<div className="empty"><Bookmark size={22}/><h2>还没有自选机会</h2><p>从机会流中添加叙事，系统会持续更新它的验证状态。</p></div>}</section>}
