'use client';

import { Activity, AlertTriangle, ArrowRight, Bookmark, Bot, Braces, ChevronRight, CircleHelp, Clock3, Database, Eye, History, Radar, Search, ShieldCheck, Sparkles, TimerReset, WalletCards, UsersRound } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { opportunities as demoOpportunities } from '@/lib/opportunity-fixtures';
import { providerLabel, type Chain, type Opportunity, type Stage } from '@/lib/opportunity';

const API = 'https://mdc-ingestion.wanglujie1987.workers.dev';
type View = '机会流' | '信源画像' | '历史研究' | '自选' | '详情';
type Live = { id:string; name:string; ticker:string|null; stage:Stage; score:number; first_seen_at:string; last_seen_at:string; independent_author_count:number; post_count:number; scan_count:number; summary:string|null; risk:string|null; dex_status:string|null; chain_id:string|null; dex_id:string|null; pair_address:string|null; token_address:string|null; liquidity_usd:number|null; market_cap_usd:number|null };
type Scan = {source:string;status:string;query_count:number;post_count:number;candidate_count:number;started_at:string;dex_deferred_count?:number}|null;
type Source = {author_handle:string;first_observed_at:string;total_signals:number;discovery_signals:number;prediction_signals:number;resolved_outcomes:number;accuracy:number|null};
type DetailData = {evidence:Array<{tweet_id:string;author_handle:string|null;observed_at:string;content:string|null;source_url:string|null}>};
const stages:Stage[]=['社媒初筛','待链上验证','未发币','候选合约','刚发币待验证','已验证未拥挤','已排除'];
const cases=[['dogwifhat','$4.8B','代币出现前 2 天'],['PNUT','$2.3B','事件爆发后 4 小时'],['CHILLGUY','$643M','模板扩散第 1 天']];

function date(value?:string|null){return value?new Intl.DateTimeFormat('zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value)):'—'}
function chain(id:string|null):Chain{return id==='bsc'?'BNB Chain':id==='solana'?'Solana':id==='robinhood'?'Robinhood Chain':'未确认'}
function mapLive(row:Live):Opportunity{const matched=Boolean(row.token_address||row.pair_address);return {id:row.id,name:row.name,ticker:row.ticker??'—',stage:row.stage,score:row.score,discovered:date(row.first_seen_at),firstObservedAt:row.first_seen_at,velocity:String(row.independent_author_count)+' 个独立账号',narrative:row.summary??'系统正在汇总叙事证据。',risk:row.risk??'尚未完成风险评估',evidence:String(row.post_count)+' 条帖子 · '+String(row.scan_count)+' 次扫描',automated:matched?'已匹配链上候选':'等待链上核验',sources:[{provider:'socialdata',platform:'x',label:String(row.post_count)+' 条可追溯 X 证据',observedAt:row.last_seen_at}],tokenCandidates:matched?[{chain:chain(row.chain_id),address:row.token_address??undefined,pairAddress:row.pair_address??undefined,dexId:row.dex_id??undefined,liquidityUsd:row.liquidity_usd??undefined,marketCapUsd:row.market_cap_usd??undefined,verified:row.dex_status==='single_match'}]:[]}}

export default function Home(){
 const [view,setView]=useState<View>('机会流'),[selected,setSelected]=useState<Opportunity>(demoOpportunities[0]),[saved,setSaved]=useState<string[]>([]),[filter,setFilter]=useState<Stage|'全部'>('全部'),[queue,setQueue]=useState<'priority'|'watch'>('priority'),[live,setLive]=useState<{opportunities:Live[];latestScan:Scan;methodology:string}|null>(null),[sources,setSources]=useState<Source[]|null>(null),[error,setError]=useState<string|null>(null);
 useEffect(()=>{let on=true;Promise.all([fetch(API+'/opportunities?limit=100').then(r=>r.ok?r.json():Promise.reject(new Error('机会接口返回 '+r.status))) as Promise<{opportunities:Live[];latestScan:Scan;methodology:string}>,fetch(API+'/sources?limit=100').then(r=>r.ok?r.json():Promise.reject(new Error('信源接口返回 '+r.status))) as Promise<{sources:Source[]}>]).then(([o,s])=>{if(on){setLive(o);setSources(s.sources??[]);setError(null)}}).catch((e:Error)=>on&&setError(e.message));return()=>{on=false}},[]);
 const items=live?live.opportunities.map(mapLive):demoOpportunities, save=(id:string)=>setSaved(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id]),open=(item:Opportunity)=>{setSelected(item);setView('详情')};
 return <main className="mdc"><header><button className="brand" onClick={()=>setView('机会流')}><span className="brandMark"><Radar size={19}/></span><span><b>Meme Discovery Channel</b><small>自动发现 · 自动验证 · 自动复盘</small></span></button><div className="engine"><i/> 多链监控运行中 <em/> BNB · SOL · ROBINHOOD</div><button className="avatar">CT</button></header><nav>{(['机会流','信源画像','历史研究','自选'] as View[]).map(x=><button key={x} onClick={()=>setView(x)} className={view===x?'on':''}>{x}</button>)}<span/><button className="search"><Search size={15}/> 搜索叙事 / 代币</button></nav>{view==='机会流'&&<Feed items={items} scan={live?.latestScan??null} methodology={live?.methodology} fallback={!live} error={error} filter={filter} setFilter={setFilter} queue={queue} setQueue={setQueue} saved={saved} save={save} open={open}/>} {view==='详情'&&<Detail item={selected} back={()=>setView('机会流')} saved={saved.includes(selected.id)} save={save}/>} {view==='信源画像'&&<Sources profiles={sources} error={error}/>} {view==='历史研究'&&<Research open={open}/>} {view==='自选'&&<Watchlist items={items} saved={saved} open={open}/>}</main>
}

function Feed({items,scan,methodology,fallback,error,filter,setFilter,queue,setQueue,saved,save,open}:{items:Opportunity[];scan:Scan;methodology?:string;fallback:boolean;error:string|null;filter:Stage|'全部';setFilter:(x:Stage|'全部')=>void;queue:'priority'|'watch';setQueue:(x:'priority'|'watch')=>void;saved:string[];save:(id:string)=>void;open:(x:Opportunity)=>void}){
 const ranked=useMemo(()=>[...items].sort((a,b)=>{const weight:{[key:string]:number}={'候选合约':5,'待链上验证':4,'未发币':3,'刚发币待验证':2,'社媒初筛':1,'已验证未拥挤':0,'已排除':-1};return (weight[b.stage]*1000+b.score)-(weight[a.stage]*1000+a.score)}),[items]);
 const filtered=filter==='全部'?ranked:ranked.filter(x=>x.stage===filter), priority=filtered.slice(0,5), watch=filtered.slice(5), shown=queue==='priority'?priority:watch, status=scan?.status==='completed'?'已完成':scan?.status==='partial'?'部分完成':scan?.status==='failed'?'失败':'等待数据';
 return <section className="frame"><section className="commandbar"><div><p className="eyebrow"><Sparkles size={13}/> AUTOMATED DISCOVERY</p><h1>不是人工盯盘。<br/><mark>系统正在找什么？</mark></h1><p>持续追踪高价值传播源、叙事加速，以及多条链上的新合约与可信池；只把可追溯的候选带到你的机会流。</p></div><div className="runStatus"><div><Activity size={17}/><span><b>最近一轮 SocialData 扫描</b><small>{scan?date(scan.started_at)+' · '+scan.source:'正在连接实时数据'}</small></span><strong>{status}</strong></div><dl><div><dt>X 查询</dt><dd>{scan?.query_count??'—'}</dd></div><div><dt>返回帖子</dt><dd>{scan?.post_count??'—'}</dd></div><div><dt>进入初筛</dt><dd>{scan?.candidate_count??'—'}</dd></div></dl></div></section>
 {fallback&&<div className="dataNotice warning"><AlertTriangle size={15}/><span><b>演示数据兜底中。</b>{error?' 实时接口暂不可用：'+error:' 正在连接实时接口。'}</span></div>}{!fallback&&items.length===0&&<div className="dataNotice"><Activity size={15}/><span><b>实时数据已连接，但尚无可展示机会。</b> 下一轮扫描会自动更新此队列。</span></div>}
 <section className="chainbar"><div><span>当前覆盖</span><b className="bnb">BNB Chain</b><b className="sol">Solana</b><b className="rh">Robinhood Chain</b><b className="more">+ 新兴链持续接入</b></div><small>叙事跨链传播时，系统将候选合约与链上状态分开验证。</small></section>
 <section className="pipeline"><p><Database size={14}/> 自动机会流水线</p><div><Step n="01" title="社媒初筛" copy="X 新帖 · 关键词 · 来源" active/><ArrowRight/><Step n="02" title="验证扩散" copy="独立作者 · 二创"/><ArrowRight/><Step n="03" title="匹配多链代币" copy="候选合约 · 可信池"/><ArrowRight/><Step n="04" title="归档结果" copy="上涨 · 失败 · 风险排除"/></div></section>
 <section className="overview"><div><p>社媒初筛</p><b>{items.filter(x=>x.stage==='社媒初筛').length}</b><small>仅为待验证线索</small></div><div><p>候选合约</p><b className="muted">{items.filter(x=>x.stage==='候选合约').length}</b><small>尚未自动认定为同项目</small></div><div><p>最近轮 X 原始帖子</p><b>{scan?.post_count??'—'}</b><small>{scan?String(scan.query_count)+' 组关键词 · 已去重待聚类':'等待实时扫描记录'}</small></div><div className="fresh"><TimerReset size={17}/><p>下一步</p><b>{scan?.dex_deferred_count?'延后 Dex 核验':'二次扫描'}</b><small>{scan?.dex_deferred_count?String(scan.dex_deferred_count)+' 个候选将自动重试':'比较独立作者与互动增速'}</small></div></section>
 <section className="feedHead"><div><p className="eyebrow"><Radar size={14}/> OPPORTUNITY QUEUE</p><h2>{queue==='priority'?'现在最值得研究的 5 个候选':'观察池：暂不抢占你的注意力'}</h2></div><p>{methodology??'排序：早期性 × 传播独立性 × 可验证性'}</p></section><div className="queueSwitch"><button className={queue==='priority'?'chosen':''} onClick={()=>setQueue('priority')}>优先研究 <b>{priority.length}/5</b></button><button className={queue==='watch'?'chosen':''} onClick={()=>setQueue('watch')}>观察池 <b>{watch.length}</b></button><small>默认仅保留 5 个候选；其余仍持续监控。</small></div><div className="filters"><button className={filter==='全部'?'chosen':''} onClick={()=>setFilter('全部')}>全部 <b>{items.length}</b></button>{stages.map(x=><button key={x} onClick={()=>setFilter(x)} className={filter===x?'chosen':''}>{x} <b>{items.filter(i=>i.stage===x).length}</b></button>)}</div>
 <div className="contentGrid"><div className="opps">{shown.length?shown.map((x,i)=><Card key={x.id} item={x} index={i} saved={saved.includes(x.id)} save={save} open={open}/>):<div className="empty"><Radar size={22}/><h2>没有符合当前筛选的实时候选</h2><p>系统会在下一轮扫描后自动刷新。</p></div>}</div><aside className="sidebar"><div className="ruleCard"><ShieldCheck size={17}/><h3>发布门槛</h3><p>社媒初筛不代表机会。只有形成独立传播，并完成 DexScreener 链上核验后，才会进入可研究队列。</p></div><div className="ruleCard warning"><AlertTriangle size={17}/><h3>本轮主要排除风险</h3><p><b>收益喊单与单账号推广</b><br/>系统不会把一条推广帖包装成早期机会。</p></div></aside></div><HistoryStrip/><AgentStory/></section>
}
function Step({n,title,copy,active=false}:{n:string;title:string;copy:string;active?:boolean}){return <article className={active?'active':''}><span>{n}</span><b>{title}</b><small>{copy}</small></article>}
function Card({item,index,saved,save,open}:{item:Opportunity;index:number;saved:boolean;save:(id:string)=>void;open:(x:Opportunity)=>void}){const c=item.tokenCandidates[0]?.chain,providers=[...new Set(item.sources.map(x=>x.provider))];return <article className={'opp stage-'+item.stage} onClick={()=>open(item)}><div className={'glyph g'+(index%5)}>{item.name[0]}</div><div className="oppbody"><div><h2>{item.name} <small>{item.ticker}</small></h2>{c&&<span className="chainTag">{c}</span>}<label>{item.stage}</label></div><p>{item.narrative}</p><aside><Clock3 size={12}/>首次发现 {item.discovered}<em/> <Activity size={12}/>{item.evidence}</aside><div className="sourceTags">{providers.map(x=><span key={x}>{providerLabel(x)}</span>)}</div></div><div className="machine"><span>{item.automated}</span><b>{item.score}</b><small>机会分</small><strong>{item.velocity}</strong></div><button className="save" onClick={e=>{e.stopPropagation();save(item.id)}}><Bookmark size={17} fill={saved?'currentColor':'none'}/></button></article>}
function Detail({item,back,saved,save}:{item:Opportunity;back:()=>void;saved:boolean;save:(id:string)=>void}){const [detail,setDetail]=useState<DetailData|null>(null);useEffect(()=>{let on=true;(fetch(API+'/opportunities/'+encodeURIComponent(item.id)).then(r=>r.ok?r.json():Promise.reject()) as Promise<DetailData>).then(x=>on&&setDetail(x)).catch(()=>on&&setDetail(null));return()=>{on=false}},[item.id]);const evidence=detail?.evidence??[];return <section className="frame detail"><button className="back" onClick={back}>← 返回机会流</button><div className="detailTitle"><div><p className="eyebrow"><CircleHelp size={14}/> AUTOMATED RESEARCH CARD</p><h1>{item.name} <mark>· {item.stage}</mark></h1><p>由自动监控生成；结论随传播结构、合约归因与链上风险实时更新。</p></div><button className="bookmark" onClick={()=>save(item.id)}><Bookmark size={16} fill={saved?'currentColor':'none'}/>{saved?'已加入自选':'加入自选'}</button></div><div className="verdict"><div><span>系统结论</span><h2>{item.stage==='未发币'?'继续追踪叙事，尚不可交易':item.stage==='已排除'?'排除：不构成可信机会':'需要进一步验证'}</h2><p>{item.risk}。本页面不是交易建议。</p></div><div><span>最大风险</span><b>{item.risk}</b></div><div><span>状态有效期</span><b>下次扫描后重估</b></div></div><section className="detailGrid"><div className="panel"><h2>机器证据链</h2>{[['叙事发现',item.discovered+' · 自动聚类完成'],['传播验证',item.evidence],['合约归因',item.tokenCandidates[0]?.chain??'尚未发现可信合约'],['链上健康度','等待池子 / 持仓数据完整']].map(([a,b],i)=><div className="evidence" key={a}><i className={i<2?'good':''}/><p><b>{a}</b>{b}</p></div>)}</div><div className="panel"><h2>来源与可追溯证据</h2>{evidence.length?evidence.map(x=><div className="evidence sourceEvidence" key={x.tweet_id}><i className="good"/><p><b>{x.author_handle?'@'+x.author_handle:'X 来源'}</b>{x.content??'原始内容保存中'}<small>{date(x.observed_at)} · {x.source_url?<a href={x.source_url} target="_blank" rel="noreferrer">查看原帖</a>:'链接暂不可用'}</small></p></div>):item.sources.map(x=><div className="evidence sourceEvidence" key={x.observedAt}><i className="good"/><p><b>{providerLabel(x.provider)}</b>{x.label}<small>{date(x.observedAt)}</small></p></div>)}</div></section></section>}
function Sources({profiles,error}:{profiles:Source[]|null;error:string|null}){return <section className="frame"><div className="researchHero"><p className="eyebrow"><UsersRound size={14}/> SOURCE INTELLIGENCE</p><h1>不把账号叫“大神”。<br/><mark>只保留可验证的信源轨迹。</mark></h1><p>系统记录一个账号在哪些叙事上首次出现、是否给出明确方向，以及这些信号在结果可验证后如何表现。</p></div><section className="sourceMethod"><ShieldCheck size={18}/><div><b>当前方法：先积累，后排名</b><p>准确率只在有足够可验证结果后展示；现在不因少量样本对账号做收益承诺或排行。</p></div></section>{profiles===null?<div className="empty"><Activity size={22}/><h2>正在读取信源画像</h2><p>{error?'接口暂不可用：'+error:'等待实时接口返回。'}</p></div>:profiles.length===0?<div className="empty"><UsersRound size={22}/><h2>信源档案正在积累</h2><p>新的候选帖子会自动形成账号画像；当前尚无足够的已入库信源记录。</p></div>:<div className="sourceTable"><div className="sourceHead"><span>账号</span><span>信号</span><span>首次发现</span><span>明确预测</span><span>结果状态</span></div>{profiles.map(x=><article key={x.author_handle}><span><b>@{x.author_handle}</b><small>收录于 {date(x.first_observed_at)}</small></span><b>{x.total_signals}</b><b>{x.discovery_signals}</b><b>{x.prediction_signals}</b><span>{x.resolved_outcomes?<><b>{x.accuracy===null?'—':Math.round(x.accuracy*100)+'%'}</b><small>{x.resolved_outcomes} 个已验证结果</small></>:<><b>积累中</b><small>尚无可验证结果</small></>}</span></article>)}</div>}</section>}
function HistoryStrip(){return <section className="historyStrip"><div className="historyTop"><div><p className="eyebrow"><History size={14}/> TOKEN REVIEW</p><h2>历史不是装饰，它决定现在的判断。</h2><p>每个样本保留“首次发现 → 发币 → 峰值 / 失败”的完整时间线。</p></div><button>进入历史研究 <ChevronRight size={15}/></button></div><div className="caseGrid">{cases.map(x=><article key={x[0]}><span>历史样本</span><div><h3>{x[0]}</h3><b>{x[1]}</b></div><p>系统首次发现：{x[2]}</p></article>)}</div></section>}
function AgentStory(){return <section className="agentStory"><div className="agentCopy"><p className="eyebrow"><Bot size={14}/> FOR EXTERNAL AGENTS · PLANNED</p><h2>当你不在看盘，<mark>Agent 也能读懂机会。</mark></h2><p>未来，每个可验证机会都会成为机器可读事件：叙事、链、合约、证据、风险与失效时间一并交给外部 Agent。</p><div className="agentBadges"><span><Braces size={14}/> 只读 Opportunity API</span><span><ShieldCheck size={14}/> 证据与风险字段</span></div></div><div className="agentFlow"><div><Radar size={19}/><b>MDC Signals</b><small>多链机会研究</small></div><ArrowRight/><div><Bot size={19}/><b>Your Agent</b><small>按你的规则判断</small></div><ArrowRight/><div><WalletCards size={19}/><b>Your Wallet</b><small>你自行授权与签名</small></div></div><footer>我们提供信号，不托管资金、不替用户交易。<span>External Agent API · 即将开放</span></footer></section>}
function Research({open}:{open:(x:Opportunity)=>void}){return <section className="frame"><div className="researchHero"><p className="eyebrow"><History size={14}/> HISTORICAL RESEARCH</p><h1>回顾代币，<mark>检验系统是否发现得够早。</mark></h1><p>这里不只收藏“涨得好”的案例，也保留失败、仿盘和被排除的样本。</p></div><div className="caseTable"><div className="tableHead"><span>代币 / 叙事</span><span>首次发现阶段</span><span>峰值市值</span><span>结果</span></div>{cases.map((x,i)=><button key={x[0]} onClick={()=>open(demoOpportunities[i])}><span><b>{x[0]}</b><small>历史样本</small></span><span>{x[2]}</span><span>{x[1]}</span><span className="positive">查看复盘<ChevronRight size={14}/></span></button>)}</div></section>}
function Watchlist({items,saved,open}:{items:Opportunity[];saved:string[];open:(x:Opportunity)=>void}){const picks=items.filter(x=>saved.includes(x.id));return <section className="frame"><div className="researchHero"><p className="eyebrow"><Eye size={14}/> WATCHLIST</p><h1>只追踪你真正关心的变化。</h1><p>系统只在合约出现、归因确认、风险升高或机会失效时更新状态。</p></div>{picks.length?<div className="opps">{picks.map((x,i)=><Card key={x.id} item={x} index={i} saved save={()=>{}} open={open}/>)}</div>:<div className="empty"><Bookmark size={22}/><h2>还没有自选机会</h2><p>从机会流中添加叙事，系统会持续更新它的验证状态。</p></div>}</section>}
