'use client';
import {useState} from 'react';
import {Activity,ArrowUpRight,Bookmark,CheckCircle2,ChevronRight,Clock3,Eye,Flame,Search,ShieldAlert,Sparkles,Target} from 'lucide-react';
type View='机会流'|'验证'|'自选';
const opportunities=[['Office Cat','萌芽','未发币','87','42 分钟前','+184%','“周一开会”灰猫从职场梗迅速外溢到 Crypto Twitter。'],['Touch Grass','$GRASS','刚发币','71','5 小时前','+321%','叙事先行，最早候选合约已出现，等待正统性验证。'],['BNB Cat in Suit','$BNBCAT','已拥挤','63','昨天 18:20','+48%','叙事充分兑现，链上热度和集中度都在上升。']];
const timeline=[['09:10','首次发现','Office Cat 在非加密圈层出现'],['10:05','传播验证','独立作者数超过追踪阈值'],['11:40','候选合约','检测到 2 个同名候选合约'],['12:00','等待验证','尚不满足正统合约判定条件']];
export default function Home(){const [view,setView]=useState<View>('机会流');const [saved,setSaved]=useState<string[]>([]);
 return <main className="mdc"><header><div className="logo"><span>◉</span><div><b>Meme Discovery Channel</b><small>发现叙事 · 验证机会 · 沉淀规律</small></div></div><div className="live"><i/> DEMO 数据模式 <em/> 09:05 22:00</div><button className="user">CT</button></header>
 <nav>{(['机会流','自选'] as View[]).map(x=><button key={x} onClick={()=>setView(x)} className={view===x?'on':''}>{x}</button>)}<span/><button className="search"><Search size={15}/> 搜索叙事 / 代币</button></nav>
 {view==='机会流'&&<Discovery saved={saved} setSaved={setSaved} onOpen={()=>setView('验证')}/>}
 {view==='验证'&&<Verify/>}
 {view==='自选'&&<Track saved={saved}/>}
 </main>}
function Discovery({saved,setSaved,onOpen}:{saved:string[],setSaved:(x:string[])=>void,onOpen:()=>void}){return <section className="frame"><div className="intro"><div><p className="kicker"><Sparkles size={14}/> OPPORTUNITY FEED</p><h1>这是什么？<br/><mark>现在还早吗？</mark></h1><p>只呈现值得研究的早期机会：叙事阶段、可信合约、相对首次发现时间与最大风险。</p></div><div className="principle"><b>先研究，后行动</b><p>不提供买卖建议；只用证据说明机会处在哪个阶段、风险在哪里。</p></div></div><div className="tabs"><button className="chosen">全部机会 <b>12</b></button><button>尚未发币 <b>4</b></button><button>刚发币待验证 <b>3</b></button><button>已验证未拥挤 <b>2</b></button><button>排除 <b>3</b></button></div><div className="cols"><div><div className="heading"><span><i/> 机会队列 <small>按「早期性 × 可验证性」排序</small></span><button>点击卡片研究 <ChevronRight size={15}/></button></div>{opportunities.map(([name,ticker,status,score,time,change,desc],i)=><article className="opp" key={name} onClick={onOpen}><div className={'glyph g'+i}>{name[0]}</div><div className="oppbody"><div><h2>{name} <small>{ticker}</small></h2><label className={'tag t'+i}>{status}</label></div><p>{desc}</p><aside><Clock3 size={12}/>系统首次发现：{time}<em/> <Activity size={12}/>当前最大风险：{i===0?'尚无可信合约':i===1?'正统性待验证':'链上拥挤'}</aside></div><div className="score"><b>{score}</b><small>机会分</small><strong>{change}</strong></div><button aria-label="自选" className="save" onClick={e=>{e.stopPropagation();setSaved(saved.includes(name)?saved.filter(x=>x!==name):[...saved,name])}}><Bookmark size={17} fill={saved.includes(name)?'currentColor':'none'}/></button></article>)}</div><aside className="right"><div className="today"><p><Target size={16}/> 现在还早吗？</p><div><span><b>04</b>尚未发币</span><span><b>03</b>刚发币</span><span><b>02</b>未拥挤</span></div><meter min="0" max="5" value="3"/><small>相对首次发现越近、传播越独立、链上结构越健康，越值得优先研究。</small></div><div className="note"><Flame size={17}/><p><b>历史相似案例</b><br/>Office Cat 与 3 个 $10M+ 案例具有“角色 + 二创 + 跨圈层”特征。</p></div></aside></div></section>}
function Verify(){return <section className="frame"><div className="pagehead"><p className="kicker"><CheckCircle2 size={14}/> OPPORTUNITY DETAIL</p><h1>Office Cat <mark>· 值不值得继续研究？</mark></h1><p>机会详情将发币前、发币后和历史相似案例放在同一张研究页中，而不是做成单独频道。</p></div><div className="stageflow"><div className="active"><span>01</span><b>发币前：值得追踪</b><p>叙事具有鲜明角色、可复制的视觉模板，且独立传播者正在增加。</p><ul><li>叙事形成度 <b>87</b></li><li>相对首次发现 <b>42 分钟</b></li><li>历史相似度 <b>78%</b></li></ul></div><div className="arrow">→</div><div><span>02</span><b>发币后：尚不可验证</b><p>尚无足够证据确认正统合约。若出现候选币，将自动补充链上健康度与拥挤度。</p><ul><li>可信合约 <b>未发现</b></li><li>链上健康度 <b>—</b></li><li>当前拥挤度 <b>低</b></li></ul></div></div><div className="evidence"><h2>现在的研究结论</h2>{[['来源','原始职场内容，非加密账户发起'],['传播','486 名独立作者 · 1.8K 二创'],['历史','与角色型 $10M+ 样本有 78% 相似度'],['最大风险','同名币或仿盘出现时，不能默认它与叙事有关'],['结论','加入自选，等待可信合约或传播结构发生变化']].map(([a,b])=><p key={a}><span>{a}</span>{b}</p>)}</div></section>}
function Track({saved}:{saved:string[]}){return <section className="frame"><div className="pagehead"><p className="kicker"><Eye size={14}/> WATCHLIST</p><h1>只追踪你真正关心的机会。</h1><p>提醒只针对关键变化：候选合约出现、正统性确认、风险激增或拥挤度变高。</p></div><div className="trackgrid"><div className="timeline"><h2>Office Cat <label>追踪中</label></h2>{timeline.map(([time,title,copy])=><div key={time}><time>{time}</time><i/><p><b>{title}</b>{copy}</p></div>)}</div><div className="followcard"><Bookmark size={18}/><h2>我的自选</h2>{saved.length?<p>{saved.join('、')} 正在追踪中。</p>:<p>从机会流添加后，这里会显示关键状态变化。</p>}<button>设置提醒 <ArrowUpRight size={15}/></button></div></div></section>}
